// JavaScript Document
 var boton = document.getElementById('add_pasajero');
 var contador = 2;
	boton.onclick = function()
 { if (contador == 7) { alert ("Sólo se permite un máximo de 6 pasajeros por reserva OnLine, si quiere agregar mas pasajeros por favor indicalo en el campo NOTAS"); var enfocar = document.getElementById('notas'); enfocar.focus() }
	 if (contador < 7){
		var fieldset = document.createElement('fieldset');
		fieldset.className = 'sixcol  column';
		fieldset.name = 'Pasajero '+contador;
		var leyenda = document.createElement('legend');
		var h2 = document.createElement('h2');
		h2.innerHTML = 'Datos del pasajero '+contador;
		var hr = document.createElement('hr');
		var labeln = document.createElement('label');
		labeln.innerHTML = 'Nombre';
		var divn = document.createElement('div');
		divn.className = 'field-container';
		var nombre = document.createElement('input');
		nombre.type = 'text';
		nombre.name = 'strNombre[]';
		nombre.placeholder = 'Nombre';
		nombre.title = 'Indique el Nombre del pasajero '+contador;
		nombre.maxlength = '20';
		nombre.required = 'yes';
		var labela = document.createElement('label');
		labela.innerHTML = 'Apellidos';
		var diva = document.createElement('div');
		diva.className = 'field-container';
		var apellidos = document.createElement('input');
		apellidos.type = 'text';
		apellidos.name = 'strApellidos[]';
		apellidos.placeholder = 'Apellidos';
		apellidos.title = 'Indique los Apellidos del pasajero '+contador;
		apellidos.required = 'yes';
		var labelp = document.createElement('label');
		labelp.innerHTML = 'DNI o Pasaporte';
		var divp = document.createElement('div');
		divp.className = 'field-container';
		var dni = document.createElement('input');
		dni.type = 'text';
		dni.name = 'strDNI[]';
		dni.placeholder = 'DNI o Pasaporte';
		dni.title = 'Indique el DNI o Pasaporte del pasajero '+contador;
		dni.required = 'yes';
		var labelfecha = document.createElement('label');
		labelfecha.innerHTML = 'Fecha de Nacimiento';
		var br = document.createElement('br');		
		var divdiacolum = document.createElement('div');
		divdiacolum.className = 'threecol column';
		var divfd = document.createElement('div');
		divfd.className = 'field-container';
		dia = document.createElement('input');
		dia.type = 'number';
		dia.name = 'intDia[]';			
		dia.placeholder = 'Día';
		dia.min = '1';
		dia.max = '31';
		dia.required = 'yes';
		dia.title = 'Introduzca el dia de su nacimiento.';
		var divmescolum = document.createElement('div');
		divmescolum.className = 'sixcol column last';
		var divfm = document.createElement('div');
		divfm.className = 'field-container';
		var mes = document.createElement('select');
		mes.name = 'strMes[]';
		mes.required = 'yes';
		mes.title = 'seleccione el mes de su nacimiento.';
		var meses = document.createElement('option');
		meses.text = 'Mes';
		meses.value = '00';
		var enero = document.createElement('option');
		enero.text = 'Enero';
		enero.value = '01';
		var febrero = document.createElement('option');
		febrero.text = 'Febrero';
		febrero.value = '02';
		var marzo = document.createElement('option');
		marzo.text = 'Marzo';
		marzo.value = '03';
		var abril = document.createElement('option');
		abril.text = 'Abril';
		abril.value = '04';
		var mayo = document.createElement('option');
		mayo.text = 'Mayo';
		mayo.value = '05';
		var junio = document.createElement('option');
		junio.text = 'Junio';
		junio.value = '06';
		var julio = document.createElement('option');
		julio.text = 'Julio';
		julio.value = '07';
		var agosto = document.createElement('option');
		agosto.text = 'Agosto';
		agosto.value = '08';
		var septiembre = document.createElement('option');
		septiembre.text = 'Septiembre';
		septiembre.value = '09';
		var octubre = document.createElement('option');
		octubre.text = 'Octubre';
		octubre.value = '10';
		var noviembre = document.createElement('option');
		noviembre.text = 'Noviembre';
		noviembre.value = '11';
		var diciembre = document.createElement('option');
		diciembre.text = 'Diciembre';
		diciembre.value = '12';
		var fecha = new Date();
		var ano = fecha.getFullYear();
		var divanocolum = document.createElement('div');
		divanocolum.className = 'threecol column';
		var divfa = document.createElement('div');
		divfa.className = 'field-container';
		var anio = document.createElement('input');
		anio.type = 'number';
		anio.name = 'intAnios[]';			
		anio.placeholder = 'Año';
		anio.min = ano-90;
		anio.max = ano;
		anio.required = 'yes';
		anio.title = 'Introduzca el año en que nacio.';
		var clientes = document.getElementById('clientes');
		clientes.appendChild(fieldset);
		fieldset.appendChild(leyenda);
		leyenda.appendChild(h2);
		fieldset.appendChild(hr);
		fieldset.appendChild(labeln);
		labeln.appendChild(divn);
		divn.appendChild(nombre);
		fieldset.appendChild(labela);
		labela.appendChild(diva);
		diva.appendChild(apellidos);
		fieldset.appendChild(labelp);
		labelp.appendChild(divp);
		divp.appendChild(dni);
		fieldset.appendChild(labelfecha);
		fieldset.appendChild(br);
		fieldset.appendChild(divdiacolum);
		divdiacolum.appendChild(divfd);
		divfd.appendChild(dia);
		fieldset.appendChild(divmescolum);
		divmescolum.appendChild(divfm);
		divfm.appendChild(mes);
		mes.appendChild(meses);
		mes.appendChild(enero);
		mes.appendChild(febrero);
		mes.appendChild(marzo);
		mes.appendChild(abril);
		mes.appendChild(mayo);
		mes.appendChild(junio);
		mes.appendChild(julio);
		mes.appendChild(agosto);
		mes.appendChild(septiembre);
		mes.appendChild(octubre);
		mes.appendChild(noviembre);
		mes.appendChild(diciembre);
		fieldset.appendChild(divanocolum);
		divanocolum.appendChild(divfa);
		divfa.appendChild(anio);
		contador = contador + 1;
	} 
 }